apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: ncp-exec-role, namespace: nsx-system}
rules:
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list]
- apiGroups: ['']
  resources: [pods/exec]
  verbs: [get, create]
